name: Deploy Web App

on: 
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      version: 
        type: string
        required: true

jobs:
  DeployWebApp:
    name: ${{ inputs.name }}
    runs-on: windows-latest

    steps:
      - name: Deploy Web App
        run:
          echo "Deploying web app ${{ inputs.name }} with version ${{ inputs.version }}"

  Dummy:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello world"
